# Generated by Django 4.2.16 on 2025-12-30 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('krishi', '0002_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('normal', 'Normal User'), ('admin', 'Admin User')], default='normal', max_length=10),
        ),
        migrations.AlterField(
            model_name='vetrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
