# Generated by Django 4.2.16 on 2026-01-22 09:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('krishi', '0003_userprofile_role_alter_vetrequest_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('picture', models.ImageField(blank=True, null=True, upload_to='news/')),
                ('date', models.DateField(auto_now_add=True)),
                ('posted_by_name', models.CharField(blank=True, help_text='Used when article is not posted by admin user', max_length=150, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('posted_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='news_articles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
