# Generated by Django 4.2.16 on 2026-01-22 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('krishi', '0004_newsarticle'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimalType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animal_name', models.CharField(max_length=100, unique=True)),
                ('remarks', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Animal Type',
                'verbose_name_plural': 'Animal Types',
            },
        ),
        migrations.AlterField(
            model_name='vetrequest',
            name='animal_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vet_requests', to='krishi.animaltype'),
        ),
    ]
