# Generated by Django 4.2.16 on 2026-02-13 11:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('krishi', '0005_animaltype_alter_vetrequest_animal_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='animaltype',
            options={'ordering': ['animal_name']},
        ),
        migrations.AlterModelOptions(
            name='vetrequest',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='vetrequest',
            name='assigned_doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='posted_by_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('normal', 'Farmer'), ('admin', 'Doctor')], default='normal', max_length=10),
        ),
        migrations.AlterField(
            model_name='vetrequest',
            name='farmer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farmer_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vetrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('doctor_cancelled', 'Doctor Cancelled'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='VetRequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Created'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('farmer_cancelled', 'Farmer Cancelled'), ('doctor_cancelled', 'Doctor Cancelled')], max_length=30)),
                ('previous_status', models.CharField(max_length=20)),
                ('new_status', models.CharField(max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('vet_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='krishi.vetrequest')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
