# Generated by Django 5.2.9 on 2026-02-12 16:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('krishi', '0005_animaltype_alter_vetrequest_animal_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='vetrequest',
            old_name='symptoms',
            new_name='problem_description',
        ),
        migrations.AddField(
            model_name='vetrequest',
            name='assigned_doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctor_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vetrequest',
            name='animal_type',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='vetrequest',
            name='farmer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farmer_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vetrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('doctor_cancelled', 'Doctor Cancelled'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
